
# =============================================================================
# General specifications for clay analysis runs
# =============================================================================

# =============================================================================
# Required Parameters
# =============================================================================

