
site_name: ClayCode
site_url: https://erastova-group.github.io/ClayCode
site_author: Valentina Erastova

repo_name: ClayCode
repo_url: https://github.com/Erastova-group/ClayCode


# Navigation
nav:
    - Home: index.md
    - Quick Start: start.md
    - Documentation: 
        - User Guide: userguide.md
        - Modules:
            - ClayCode.builder: builder.md
            - ClayCode.simpinp: siminp.md

        - INPUT files: 
            - YAML: YAML.md
            - CSV: CSV.md
        - OUTPUT files: output.md

    - Tutorials: 
        - Tutorials: tutorials.md
        - Clays:
            - Montmorillonite: mmt.md
            - Illite: imt.md 
            - Pyrophylite: pyr.md
            - Nontronite: nont.md
            - Fe-smectite: swa.md
            - Kaolinite: kao.md
            - LDH: ldh.md
    - Developers Guide: developers.md

# set up theme
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
    collapse_navigation: true
    titles_only: false
    navigation_depth: 4
    sticky_navigation: true
 
# math
extra_javascript: 
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - footnotes


plugins:
  - search
  - bibtex:
      bib_file: "./docs/refs.bib"





