[project]
name = "ClayCode"
version = "0.1.1"
description = "A python package for building clay models and analysing MD simulation data of clay systems"
authors = [{ name = "Hannah Pollak", email = "h.pollak@sms.ed.ac.uk" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = ['matplotlib>=3.6.2',
    'mdanalysis==2.3',
    'numpy>=1.23.5',
    'pandas>=1.5.2',
    'pyyaml>=6',
    'scipy>=1.9.3',
    'tqdm>=4.43.0',
    'parmed>=4.1'
    ]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"
]

[project.scripts]
ClayCode = "ClayCode:__main__.run"

[tool.setuptools.packages.find]
where=['package']

[tool.setuptools]
# ...
# By default, include-package-data is true in pyproject.toml, so you do
# NOT have to specify this line.
include-package-data = true

[tool.setuptools.package-data]
"ClayAnalysis.data" = ['**/*.top', '**/*.gro', '**/*.itp', '**/*/mdp',
'**/*.yaml', '**/*.csv', '**/*.atp', '**/*.ndx']
"ClayAnalysis.builder.config" = ['*.yaml']

[project.urls]
"Homepage" = "https://github.com/Erastova-group/ClayCode.git"

[build-system]
requires = ["setuptools>=62", "importlib_resources"]
build-backend = "setuptools.build_meta"
