# =============================================================================
# Default specifications for adding molecules to clay system bulk
# =============================================================================

# -----------------------------------------------------------------------------
# Force Field Specifications
# -----------------------------------------------------------------------------

# force field selections
FF:
  CLAY: ClayFF_Fe
  IONS: Ions
  AA: charmm36
  # SPC water from ClayFF
  WATER: SPC

NEUTRAL_IONS:
    'Na': 1
    'Cl': -1

# -----------------------------------------------------------------------------
# bash alias for used GROMACS version
# -----------------------------------------------------------------------------

GMX: gmx


