#!/usr/bin/env python3
from __future__ import annotations

import logging
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

from ClayCode.core import (
    ArgsFactory,
    BasicPath,
    BasicPathList,
    BuildArgs,
    Definition,
    Dir,
    DirFactory,
    FFDir,
    FFList,
    File,
    FileFactory,
    FileList,
    ForceField,
    GROFile,
    GROList,
    ITPFile,
    ITPList,
    MDPFile,
    MDPList,
    MoleculeParameter,
    MoleculeParameters,
    Parameter,
    ParameterBase,
    ParameterFactory,
    Parameters,
    ParametersBase,
    ParametersFactory,
    PathFactory,
    PathList,
    PathListFactory,
    SimDir,
    SiminpArgs,
    SystemParameter,
    SystemParameters,
    TOPFile,
    TOPList,
    YAMLFile,
    parser,
)
from ClayCode.core.cctypes import (
    AnyDict,
    AnyDir,
    AnyFile,
    FileNameMatchSelector,
    PathOrStr,
    PathType,
    StrNum,
    StrNumOrListDictOf,
    StrOrListDictOf,
    StrOrListOf,
)
from ClayCode.core.log import ClayCodeLogger

__all__ = [
    "ClayCodeLogger",
    "StrOrListOf",
    "StrOrListDictOf",
    "StrNum",
    "StrNumOrListDictOf",
    "FileNameMatchSelector",
    "AnyFile",
    "AnyDir",
    "PathType",
    "PathOrStr",
    "AnyDict",
    "Definition",
    "File",
    "FileList",
    "Dir",
    "MDPFile",
    "GROList",
    "ITPList",
    "ITPFile",
    "MDPList",
    "YAMLFile",
    "FFDir",
    "ForceField",
    "TOPFile",
    "GROFile",
    "FFList",
    "PathList",
    "PathFactory",
    "ParameterFactory",
    "Parameter",
    "Parameters",
    "ParametersFactory",
    "MoleculeParameter",
    "BasicPathList",
    "BasicPath",
    "SimDir",
    "TOPList",
    "ParameterBase",
    "ParametersBase",
    "PathListFactory",
    "SystemParameters",
    "MoleculeParameters",
    "SystemParameter",
    "SiminpArgs",
    "parser",
    "BuildArgs",
    "ArgsFactory",
    "DirFactory",
    "FileFactory",
]
logging.setLoggerClass(ClayCodeLogger)
# from Bio import BiopythonDeprecationWarning
