# =============================================================================
# Default specifications for clay model construction
# =============================================================================

# -----------------------------------------------------------------------------
# General specifications 
# -----------------------------------------------------------------------------

# new - a new clay model is constructed
BUILD: new


# -----------------------------------------------------------------------------
# Clay Sheet and Interlayer Specifications
# -----------------------------------------------------------------------------

# number of unit cells in x direction
X_CELLS: 5

# number of unit cells in y direction
Y_CELLS: 5

# number of unit cells in z direction
N_SHEETS: 3

# ----------------------------------------------------------------------------
# Optional Unit Cell Composition and Ratios input
# -----------------------------------------------------------------------------

IL_ION_RATIOS:
  Ca: 1
  Cl: 1

# -----------------------------------------------------------------------------

# interlayer solvent present or not
# IL_SOLV: True

# -----------------------------------------------------------------------------
# Interlayer Ion Specification Options (comment the other options!)
# -----------------------------------------------------------------------------

# 3. Waters per unit cell (BOX_WATERS)
UC_WATERS: 20

DEFAULT_D_SPACE: 2

# -----------------------------------------------------------------------------
# Simulation Box Specifications
# -----------------------------------------------------------------------------

# full simulation box height in nm
BOX_HEIGHT: 15.0

# -----------------------------------------------------------------------------
# Solvation and Bulk Ions Specifications
# -----------------------------------------------------------------------------

# Bulk solvent added or not
BULK_SOLV: True

# Ion species and concentration in mol/L name to add in bulk solvent
BULK_IONS:
  'Na': 0.0
  'Cl': 0.0


# -----------------------------------------------------------------------------
# Simulation Runs Specifications
# -----------------------------------------------------------------------------

# select where EM and EQ should be run
MDRUNS_REMOTE: False

# Target d-spacing in A
D_SPACE: 19.5

# -----------------------------------------------------------------------------
# Force Field Specifications
# -----------------------------------------------------------------------------

# force field selections
FF:
  CLAY: ClayFF_Fe
  IONS: AmberIons
  AA: charmm36
  # SPC water from ClayFF
  WATER: SPC

# -----------------------------------------------------------------------------
# bash alias for used GROMACS version
# -----------------------------------------------------------------------------

GMX: gmx

# -----------------------------------------------------------------------------
# Parameters for stoichiometry matching
# -----------------------------------------------------------------------------

# maximum occupancy/charge deviation unit cell that is
# adjusted without querying to match expected values
# e.g. with OCC_TOL = 0.1, with and expected tetrahedral occupancy of 4.0,
# any composition with tetrahedral occupancies between 3.9 and 4.1 will be
# automatically adjusted to match the expected value
OCC_TOL: 0.1

# Occupancy threshold below which the matched composition will be set to 0
# if the element is not found in the force field or in the unit cell database
ZERO_THRESHOLD: 0.05

# Priority when correcting charges and substitution occupancies.
# e.g. with a specified octahedral charge of -0.3 and a 'mgo' occupancy of
# 0.4 is not possible and one of the two needs to be adjusted.
# Available options:
# 1. 'charges': Will conserve specified charges and adjust substitution
#               occupancies, i.e. 'mgo' (0.4) -> (0.3)
# 2. 'occupancies': Will conserve occupancies and adjust charges
#                   i.e. octahedral charge (-0.3 e) -> (-0.4 e)
SEL_PRIORITY: occupancies

# Priority when individual sheet and total charge do not match.
# e.g. total charge: -1.00, tetrahedral charge: -0.70, octahedral charge: -0.40
# Avaialble options:
# 1. 'total_charge: Will adjust tetrahedral and octahedral occupancies
#          i.e. tetrahedral charge (-0.70 e) -> (-0.65 e)
#               octahedral charge (-0.40 e) -> (-0.35 e)
# 2. 'sheet_charges': Will adjust total charge to sheet charges
#          i.e. total charge (-1.00 e) -> (1.10 e)
CHARGE_PRIORITY: total_charge

# -----------------------------------------------------------------------------
# Parameters for EM run
# -----------------------------------------------------------------------------

#MDP_PRMS: 'mdp_prms.mdp'

# -----------------------------------------------------------------------------
# Parameters for interlayer solvation increments
# -----------------------------------------------------------------------------

Z_PADDING: 0.5  # A
