name: ci
on: 
  push:
    branches:
      - main
      - gh-pages
      - website-edits
  pull_request:
    branches:
      - main
      - gh-pages
      - website-edits
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-bibtex python-markdown-math
      - run: mkdocs gh-deploy --force

